---
name: Docker Image CI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Login to Docker Hub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        username: ${{ secrets['DOCKERHUB_USERNAME'] }}
        password: ${{ secrets['DOCKERHUB_TOKEN'] }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      with:
        images: teampass/teampass
    - name: Build and push Docker image
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      with:
        context: .
        push: true
        tags: ${{ github['ref_name'] }}
        labels: ${{ steps['meta']['outputs']['labels'] }}
